### ISSUE TITLE
Add notification when live on Youtube

### ISSUE THREAD

**Issue by Its-Kenta** [unitoftime/nootbot#11]
A lot of requests have been pushed through to have some sort of notification on Discord when you're live on YT.

Best way to avoid spam with @everyone to those who are not interested is to have NootBot send message to subscribed users (ticked with reactions to NootBots message in #announcement channel to subscribe?) and send a message with @ to everyone who reacted to a reaction for Yes to receive messages reminding them that UnitOfTime is now live! <CHANNEL LINK HERE>

**Comment by unitoftime** [comment]
closed in #13
